// CivicLens SA — Seed Database API Route
// Seeds the SQLite database with realistic SA government data

import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

export async function POST() {
  try {
    // Seed Municipalities
    const municipalities = [
      { code: 'CPT', name: 'City of Cape Town', category: 'A', province: 'Western Cape', district: null, population2022: 4778553, geographicAreaKm2: 2461, wardCount: 116, financialHealthScore: 72, serviceDeliveryScore: 25, socioEconomicIndex: 35, procurementScore: 68, auditOutcome: 'Unqualified', auditYear: '2023/24', operatingBudget: 61200000000, capitalBudget: 8900000000, cashCoverageDays: 89, debtorCollectionRate: 95.2, waterAccess: 98.5, sanitationAccess: 94.2, electricityAccess: 96.8, refuseRemoval: 92.1, povertyRate: 22.4, youthUnemployment: 34.1, sassaDependency: 18.2, section139Status: 'None', earlyAlertScore: 12, climateRiskScore: 45 },
      { code: 'JHB', name: 'City of Johannesburg', category: 'A', province: 'Gauteng', district: null, population2022: 5783200, geographicAreaKm2: 1645, wardCount: 135, financialHealthScore: 48, serviceDeliveryScore: 42, socioEconomicIndex: 40, procurementScore: 52, auditOutcome: 'Qualified', auditYear: '2023/24', operatingBudget: 75400000000, capitalBudget: 11200000000, cashCoverageDays: 32, debtorCollectionRate: 78.5, waterAccess: 92.1, sanitationAccess: 88.5, electricityAccess: 91.3, refuseRemoval: 78.9, povertyRate: 31.2, youthUnemployment: 42.8, sassaDependency: 22.5, section139Status: 'Warning', earlyAlertScore: 55, climateRiskScore: 38 },
      { code: 'ETH', name: 'eThekwini', category: 'A', province: 'KwaZulu-Natal', district: null, population2022: 3634100, geographicAreaKm2: 2297, wardCount: 110, financialHealthScore: 38, serviceDeliveryScore: 55, socioEconomicIndex: 52, procurementScore: 42, auditOutcome: 'Qualified', auditYear: '2023/24', operatingBudget: 52300000000, capitalBudget: 7800000000, cashCoverageDays: 21, debtorCollectionRate: 68.3, waterAccess: 85.2, sanitationAccess: 78.4, electricityAccess: 87.6, refuseRemoval: 72.5, povertyRate: 38.6, youthUnemployment: 48.2, sassaDependency: 28.3, section139Status: 'Warning', earlyAlertScore: 68, climateRiskScore: 62 },
      { code: 'TSH', name: 'City of Tshwane', category: 'A', province: 'Gauteng', district: null, population2022: 3275000, geographicAreaKm2: 6298, wardCount: 107, financialHealthScore: 42, serviceDeliveryScore: 38, socioEconomicIndex: 33, procurementScore: 55, auditOutcome: 'Unqualified', auditYear: '2023/24', operatingBudget: 44100000000, capitalBudget: 6500000000, cashCoverageDays: 28, debtorCollectionRate: 82.1, waterAccess: 95.3, sanitationAccess: 91.2, electricityAccess: 93.7, refuseRemoval: 85.6, povertyRate: 25.8, youthUnemployment: 38.5, sassaDependency: 19.4, section139Status: 'Warning', earlyAlertScore: 48, climateRiskScore: 35 },
      { code: 'EKU', name: 'Ekurhuleni', category: 'A', province: 'Gauteng', district: null, population2022: 3178000, geographicAreaKm2: 1923, wardCount: 101, financialHealthScore: 35, serviceDeliveryScore: 48, socioEconomicIndex: 45, procurementScore: 38, auditOutcome: 'Disclaimer', auditYear: '2023/24', operatingBudget: 38900000000, capitalBudget: 5600000000, cashCoverageDays: 15, debtorCollectionRate: 62.4, waterAccess: 88.7, sanitationAccess: 82.1, electricityAccess: 89.5, refuseRemoval: 74.3, povertyRate: 34.2, youthUnemployment: 45.8, sassaDependency: 25.1, section139Status: 'Intervention', earlyAlertScore: 78, climateRiskScore: 42 },
      { code: 'BUF', name: 'Buffalo City', category: 'B', province: 'Eastern Cape', district: null, population2022: 755200, geographicAreaKm2: 2568, wardCount: 50, financialHealthScore: 28, serviceDeliveryScore: 62, socioEconomicIndex: 68, procurementScore: 32, auditOutcome: 'Qualified', auditYear: '2023/24', operatingBudget: 6800000000, capitalBudget: 1200000000, cashCoverageDays: 8, debtorCollectionRate: 52.3, waterAccess: 78.4, sanitationAccess: 65.2, electricityAccess: 82.1, refuseRemoval: 58.3, povertyRate: 48.5, youthUnemployment: 55.2, sassaDependency: 35.8, section139Status: 'Intervention', earlyAlertScore: 82, climateRiskScore: 55 },
      { code: 'MAN', name: 'Mangaung', category: 'B', province: 'Free State', district: null, population2022: 789600, geographicAreaKm2: 6283, wardCount: 52, financialHealthScore: 22, serviceDeliveryScore: 68, socioEconomicIndex: 62, procurementScore: 28, auditOutcome: 'Disclaimer', auditYear: '2023/24', operatingBudget: 7200000000, capitalBudget: 980000000, cashCoverageDays: 5, debtorCollectionRate: 45.6, waterAccess: 72.3, sanitationAccess: 58.7, electricityAccess: 78.9, refuseRemoval: 52.1, povertyRate: 52.1, youthUnemployment: 58.4, sassaDependency: 38.2, section139Status: 'Intervention', earlyAlertScore: 88, climateRiskScore: 48 },
      { code: 'NMB', name: 'Nelson Mandela Bay', category: 'B', province: 'Eastern Cape', district: null, population2022: 1201300, geographicAreaKm2: 1959, wardCount: 60, financialHealthScore: 32, serviceDeliveryScore: 55, socioEconomicIndex: 58, procurementScore: 45, auditOutcome: 'Qualified', auditYear: '2023/24', operatingBudget: 10200000000, capitalBudget: 1800000000, cashCoverageDays: 12, debtorCollectionRate: 58.7, waterAccess: 82.1, sanitationAccess: 74.5, electricityAccess: 85.3, refuseRemoval: 68.9, povertyRate: 42.3, youthUnemployment: 52.1, sassaDependency: 32.5, section139Status: 'Warning', earlyAlertScore: 72, climateRiskScore: 40 },
      { code: 'STE', name: 'Stellenbosch', category: 'B', province: 'Western Cape', district: 'Cape Winelands', population2022: 178500, geographicAreaKm2: 862, wardCount: 19, financialHealthScore: 82, serviceDeliveryScore: 18, socioEconomicIndex: 22, procurementScore: 75, auditOutcome: 'Clean', auditYear: '2023/24', operatingBudget: 2800000000, capitalBudget: 620000000, cashCoverageDays: 120, debtorCollectionRate: 97.5, waterAccess: 99.2, sanitationAccess: 97.8, electricityAccess: 98.5, refuseRemoval: 96.2, povertyRate: 15.2, youthUnemployment: 24.8, sassaDependency: 12.5, section139Status: 'None', earlyAlertScore: 5, climateRiskScore: 32 },
      { code: 'RUST', name: 'Rustenburg', category: 'B', province: 'North West', district: 'Bojanala', population2022: 528900, geographicAreaKm2: 3542, wardCount: 32, financialHealthScore: 40, serviceDeliveryScore: 50, socioEconomicIndex: 45, procurementScore: 42, auditOutcome: 'Qualified', auditYear: '2023/24', operatingBudget: 5400000000, capitalBudget: 980000000, cashCoverageDays: 22, debtorCollectionRate: 65.8, waterAccess: 85.3, sanitationAccess: 78.9, electricityAccess: 88.5, refuseRemoval: 72.6, povertyRate: 36.2, youthUnemployment: 46.5, sassaDependency: 27.8, section139Status: 'Warning', earlyAlertScore: 52, climateRiskScore: 45 },
      { code: 'SOL', name: 'Sol Plaatje', category: 'B', province: 'Northern Cape', district: 'Frances Baard', population2022: 248900, geographicAreaKm2: 5185, wardCount: 24, financialHealthScore: 45, serviceDeliveryScore: 42, socioEconomicIndex: 48, procurementScore: 58, auditOutcome: 'Unqualified', auditYear: '2023/24', operatingBudget: 3200000000, capitalBudget: 560000000, cashCoverageDays: 35, debtorCollectionRate: 72.5, waterAccess: 90.5, sanitationAccess: 85.2, electricityAccess: 92.1, refuseRemoval: 78.4, povertyRate: 32.5, youthUnemployment: 42.3, sassaDependency: 24.6, section139Status: 'None', earlyAlertScore: 35, climateRiskScore: 68 },
      { code: 'MSU', name: 'Msunduzi', category: 'B', province: 'KwaZulu-Natal', district: 'Umgungundlovu', population2022: 678200, geographicAreaKm2: 649, wardCount: 37, financialHealthScore: 30, serviceDeliveryScore: 58, socioEconomicIndex: 55, procurementScore: 35, auditOutcome: 'Adverse', auditYear: '2023/24', operatingBudget: 6200000000, capitalBudget: 890000000, cashCoverageDays: 10, debtorCollectionRate: 55.2, waterAccess: 80.2, sanitationAccess: 72.1, electricityAccess: 83.5, refuseRemoval: 62.4, povertyRate: 44.8, youthUnemployment: 53.6, sassaDependency: 34.1, section139Status: 'Intervention', earlyAlertScore: 80, climateRiskScore: 52 },
    ];

    for (const muni of municipalities) {
      await db.municipality.upsert({
        where: { code: muni.code },
        update: muni,
        create: muni,
      });
    }

    // Seed Tenders
    const tenders = [
      { ocid: 'OCDS-123456-001', title: 'Provision of Water and Sanitation Infrastructure Upgrades — Phase 3', description: 'The City of Cape Town invites bids for the provision of water and sanitation infrastructure upgrades in Khayelitsha and Mitchell\'s Plain.', status: 'Active', buyerName: 'City of Cape Town', buyerId: 'CPT', municipalityCode: 'CPT', category: 'Water & Sanitation', estimatedValue: 245000000, currency: 'ZAR', publishedDate: new Date('2026-02-15'), closingDate: new Date('2026-04-15'), province: 'Western Cape', bbbeeRequirement: 'Level 1-2', contractPeriodDays: 730, aiSummary: 'Major infrastructure tender from a financially healthy metro. B-BBEE Level 1-2 required. Closing in 6 weeks.', bidRecommendation: 'Consider bidding', confidenceScore: 0.78 },
      { ocid: 'OCDS-123456-002', title: 'IT Infrastructure Modernisation and Cloud Migration Services', description: 'eThekwini Municipality seeks qualified IT service providers for the modernisation of legacy systems.', status: 'Active', buyerName: 'eThekwini Municipality', buyerId: 'ETH', municipalityCode: 'ETH', category: 'IT & Technology', estimatedValue: 185000000, currency: 'ZAR', publishedDate: new Date('2026-02-20'), closingDate: new Date('2026-03-30'), province: 'KwaZulu-Natal', bbbeeRequirement: 'Level 1-3', contractPeriodDays: 1095, aiSummary: 'High-value IT modernisation tender. Buyer has financial health concerns (FHS: 38/100).', bidRecommendation: 'Bid with caution', confidenceScore: 0.62 },
      { ocid: 'OCDS-123456-003', title: 'Construction of New Primary School — Soshanguve Block XX', description: 'Department of Education, Gauteng Province, invites bids for the design and construction of a new primary school facility.', status: 'Active', buyerName: 'Gauteng Department of Education', buyerId: null, municipalityCode: 'TSH', category: 'Education', estimatedValue: 95000000, currency: 'ZAR', publishedDate: new Date('2026-01-28'), closingDate: new Date('2026-03-28'), province: 'Gauteng', bbbeeRequirement: 'Level 1-4', contractPeriodDays: 540, aiSummary: 'Standard school construction tender. Good entry point for mid-size construction firms.', bidRecommendation: 'Strong bid opportunity', confidenceScore: 0.85 },
      { ocid: 'OCDS-123456-004', title: 'Supply and Installation of Solar PV Systems — Municipal Buildings', description: 'Mangaung Metropolitan Municipality seeks providers for solar PV systems at 15 municipal buildings.', status: 'Active', buyerName: 'Mangaung Metropolitan Municipality', buyerId: 'MAN', municipalityCode: 'MAN', category: 'Energy', estimatedValue: 78000000, currency: 'ZAR', publishedDate: new Date('2026-02-10'), closingDate: new Date('2026-04-10'), province: 'Free State', bbbeeRequirement: 'Level 1-2', contractPeriodDays: 365, aiSummary: 'Green energy tender from Mangaung, under Section 139 intervention. High risk.', bidRecommendation: 'High risk — proceed only with guarantees', confidenceScore: 0.45 },
      { ocid: 'OCDS-123456-005', title: 'Professional Consulting Services for IDP Review', description: 'Buffalo City Metropolitan Municipality requires consulting services for the review of its Integrated Development Plan.', status: 'Awarded', buyerName: 'Buffalo City Metropolitan Municipality', buyerId: 'BUF', municipalityCode: 'BUF', category: 'Professional Services', estimatedValue: 12000000, awardValue: 10500000, currency: 'ZAR', publishedDate: new Date('2025-11-15'), closingDate: new Date('2025-12-20'), awardDate: new Date('2026-01-15'), province: 'Eastern Cape', bbbeeRequirement: 'Level 1-3', contractPeriodDays: 270, aiSummary: 'IDP consulting tender awarded to a Level 1 B-BBEE firm.' },
      { ocid: 'OCDS-123456-006', title: 'Road Rehabilitation and Resealing Programme — Ward 1 to Ward 20', description: 'Rustenburg Local Municipality invites bids for the rehabilitation and resealing of 120km of roads.', status: 'Active', buyerName: 'Rustenburg Local Municipality', buyerId: 'RUST', municipalityCode: 'RUST', category: 'Infrastructure', estimatedValue: 320000000, currency: 'ZAR', publishedDate: new Date('2026-02-25'), closingDate: new Date('2026-04-25'), province: 'North West', bbbeeRequirement: 'Level 1-4', contractPeriodDays: 900, aiSummary: 'Large-scale road infrastructure programme. Previous tenders showed 30% cost overruns on average.', bidRecommendation: 'Bid with detailed risk pricing', confidenceScore: 0.58 },
      { ocid: 'OCDS-123456-007', title: 'Supply of Medical Equipment and Consumables — 3-Year Contract', description: 'Gauteng Department of Health seeks suppliers for medical equipment and consumables to 12 hospitals.', status: 'Active', buyerName: 'Gauteng Department of Health', buyerId: null, municipalityCode: null, category: 'Healthcare', estimatedValue: 450000000, currency: 'ZAR', publishedDate: new Date('2026-02-18'), closingDate: new Date('2026-04-18'), province: 'Gauteng', bbbeeRequirement: 'Level 1-3', contractPeriodDays: 1095, aiSummary: 'Major healthcare supply contract. Buyer has history of irregular expenditure patterns.', bidRecommendation: 'Bid with robust compliance package', confidenceScore: 0.65 },
      { ocid: 'OCDS-123456-008', title: 'Security Services for Municipal Infrastructure — 24/7 Guarding', description: 'Ekurhuleni Metropolitan Municipality requires 24/7 security guarding services for water treatment plants and substations.', status: 'Cancelled', buyerName: 'Ekurhuleni Metropolitan Municipality', buyerId: 'EKU', municipalityCode: 'EKU', category: 'Security', estimatedValue: 68000000, currency: 'ZAR', publishedDate: new Date('2025-12-01'), closingDate: new Date('2026-01-15'), province: 'Gauteng', bbbeeRequirement: 'Level 1-2', contractPeriodDays: 730, aiSummary: 'This tender was cancelled — likely due to specification irregularities.' },
    ];

    for (const tender of tenders) {
      await db.tender.upsert({
        where: { ocid: tender.ocid },
        update: tender,
        create: tender,
      });
    }

    // Seed Risk Signals
    const riskSignals = [
      { type: 'Award Concentration', severity: 'High', description: 'Unusual pattern detected: 72% of awards from this buyer directed to a single supplier over 24 months', entityId: 'EKU', entityType: 'Buyer', municipalityCode: 'EKU', indicator: 'Award Concentration Index', indicatorValue: 0.72, threshold: 0.50, status: 'Active' },
      { type: 'Consecutive Awards', severity: 'Medium', description: 'Same supplier received consecutive awards in the same category for 4 periods without competitive bidding', entityId: 'CSD-002', entityType: 'Supplier', municipalityCode: 'ETH', indicator: 'Consecutive Award Count', indicatorValue: 4, threshold: 3, status: 'Active' },
      { type: 'Sub-threshold Splitting', severity: 'Critical', description: 'Multiple small awards to the same supplier within 30 days, potentially structured to avoid competitive threshold', entityId: 'CSD-005', entityType: 'Supplier', municipalityCode: 'JHB', indicator: 'Sub-threshold Award Count', indicatorValue: 7, threshold: 3, status: 'Active' },
      { type: 'Financial Distress', severity: 'Critical', description: 'Municipality cash coverage below 10 days and debtor collection below 60% — significant financial distress signal', entityId: 'MAN', entityType: 'Municipality', municipalityCode: 'MAN', indicator: 'Cash Coverage Days', indicatorValue: 5, threshold: 30, status: 'Active' },
      { type: 'Audit Regression', severity: 'High', description: 'Municipality audit outcome has regressed from Qualified to Disclaimer over two consecutive years', entityId: 'EKU', entityType: 'Municipality', municipalityCode: 'EKU', indicator: 'Audit Trajectory', indicatorValue: -2, threshold: -1, status: 'Active' },
    ];

    for (const signal of riskSignals) {
      await db.riskSignal.create({ data: signal });
    }

    return NextResponse.json({
      success: true,
      message: 'Database seeded successfully',
      counts: {
        municipalities: municipalities.length,
        tenders: tenders.length,
        riskSignals: riskSignals.length,
      },
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { error: 'Failed to seed database', details: String(error) },
      { status: 500 }
    );
  }
}
